// gen-graphic-layers.test.mts — the tiledata reader behind app/vault-lib.mts's wearable-graphic table.
// Tags are name prefixes: [smoke] [fast] [slow]. Run: node --test scripts/gen-graphic-layers.test.mts
import { test } from "node:test";
import assert from "node:assert/strict";
import { wearableLayers, runsOf, spliceTable } from "./gen-graphic-layers.mts";

const LAND_BYTES = 512 * (4 + 32 * 30);
const ITEM_BLOCK = 4 + 32 * 41;
// A 7.x tiledata.mul with one item block; `entries` sets [graphic, flags, layer].
function tiledata(entries: Array<[number, bigint, number]>): Buffer {
  const buf = Buffer.alloc(LAND_BYTES + ITEM_BLOCK);
  for (const [g, flags, layer] of entries) {
    const at = LAND_BYTES + 4 + g * 41;
    buf.writeBigUInt64LE(flags, at);
    buf[at + 9] = layer;
  }
  return buf;
}

test("[fast] gen-graphic-layers: keeps wearable gear graphics with their layer and collapses runs", () => {
  const W = 0x400000n;
  const buf = tiledata([[3, W, 6], [4, W | 0x2n, 6], [5, W, 19], [6, W, 11], [7, 0x2n, 6], [9, W, 6]]);
  assert.deepEqual(wearableLayers(buf), [[3, 6], [4, 6], [5, 19], [9, 6]], "hair (11) and a non-wearable graphic are left out");
  assert.deepEqual(runsOf(wearableLayers(buf)), [[3, 2, 6], [5, 1, 19], [9, 1, 6]]);
});

test("[fast] gen-graphic-layers: refuses a file that is not the 7.x layout", () => {
  assert.throws(() => wearableLayers(Buffer.alloc(LAND_BYTES + 100)), /not a 7\.x tiledata/);
});

test("[fast] gen-graphic-layers: rewrites only the marked block", () => {
  const src = "a\n// BEGIN generated by scripts/gen-graphic-layers.mts\nold\n// END generated\nb\n";
  const out = spliceTable(src, [[3, 2, 6]]);
  assert.match(out, /^a\n\/\/ BEGIN generated/);
  assert.match(out, /\[\n {2}\[3,2,6\],\n\];\n\/\/ END generated\nb\n$/);
  assert.doesNotMatch(out, /old/);
});
