// gen-graphic-layers.mts — regenerate the wearable-graphic table in app/vault-lib.mts from a client's
// tiledata.mul. The client files each item graphic's art with flags and, for a wearable, the paperdoll
// layer it goes on; the table is what lets classify() put an unequipped piece in its real slot when the
// name does not say (a named artifact, or a set whose pieces are all called "Armor").
//
// Usage: node scripts/gen-graphic-layers.mts <path to tiledata.mul>
// It rewrites only the block between the BEGIN/END markers in app/vault-lib.mts. Reads the 7.x
// ("high seas") tiledata layout only: 512 land blocks of 32 x 30 bytes, then item blocks of 32 x 41
// bytes, each block led by a 4-byte header. An older client's file has a different size and is refused.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const LAND_BYTES = 512 * (4 + 32 * 30);
const ITEM_BYTES = 41;
const ITEM_BLOCK = 4 + 32 * ITEM_BYTES;
const WEARABLE = 0x400000n;
// Layers that are a piece of gear: hair (11), face (15), beard (16), backpack (21) and mount (25) are not.
const GEAR_LAYERS = new Set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 17, 18, 19, 20, 22, 23, 24]);

// [graphic, layer] for every wearable gear graphic, in graphic order.
export function wearableLayers(buf: Buffer): Array<[number, number]> {
  if (buf.length <= LAND_BYTES || (buf.length - LAND_BYTES) % ITEM_BLOCK !== 0) throw new Error(`not a 7.x tiledata.mul (${buf.length} bytes)`);
  const count = ((buf.length - LAND_BYTES) / ITEM_BLOCK) * 32;
  const out: Array<[number, number]> = [];
  for (let g = 0; g < count; g++) {
    const at = LAND_BYTES + Math.floor(g / 32) * ITEM_BLOCK + 4 + (g % 32) * ITEM_BYTES;
    const layer = buf[at + 9]!;
    if ((buf.readBigUInt64LE(at) & WEARABLE) !== 0n && GEAR_LAYERS.has(layer)) out.push([g, layer]);
  }
  return out;
}

// Consecutive graphics on the same layer collapse to one [first graphic, count, layer] run.
export function runsOf(pairs: Array<[number, number]>): Array<[number, number, number]> {
  const runs: Array<[number, number, number]> = [];
  for (const [g, layer] of pairs) {
    const last = runs[runs.length - 1];
    if (last && last[0] + last[1] === g && last[2] === layer) last[1]++;
    else runs.push([g, 1, layer]);
  }
  return runs;
}

const BEGIN = "// BEGIN generated by scripts/gen-graphic-layers.mts";
const END = "// END generated";
export function spliceTable(source: string, runs: Array<[number, number, number]>): string {
  const from = source.indexOf(BEGIN), to = source.indexOf(END);
  if (from < 0 || to < from) throw new Error("vault-lib.mts has no generated-table markers");
  const rows: string[] = [];
  for (let i = 0; i < runs.length; i += 16) rows.push("  " + runs.slice(i, i + 16).map((r) => `[${r.join(",")}]`).join(",") + ",");
  const body = `${BEGIN}\nconst GRAPHIC_LAYER_RUNS: ReadonlyArray<readonly [number, number, number]> = [\n${rows.join("\n")}\n];\n`;
  return source.slice(0, from) + body + source.slice(to);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const file = process.argv[2];
  if (!file) { console.error("usage: node scripts/gen-graphic-layers.mts <path to tiledata.mul>"); process.exit(2); }
  const lib = join(dirname(dirname(fileURLToPath(import.meta.url))), "app", "vault-lib.mts");
  const runs = runsOf(wearableLayers(readFileSync(file)));
  writeFileSync(lib, spliceTable(readFileSync(lib, "utf8"), runs));
  console.log(`${runs.length} runs written to ${lib}`);
}
