// test-index.mts — the index of test files in TESTING.md: each test file with the first sentence of its header.
//
// A test file describes itself in its header: a `.test.mts` file in its leading `//` comment, whose first line is `// <name> — <summary>`, and an adapter's `test_*.py` in its module docstring, whose first line is `"""<name> -- <summary>`. The summary's first sentence is the index entry. The index sits in TESTING.md between the two marker lines below.
//
//   node scripts/test-index.mts           print the index
//   node scripts/test-index.mts --write   rewrite TESTING.md's index
//   node scripts/test-index.mts --check   exit 1 when TESTING.md's index is out of date
//
// scripts/test-index.test.mts holds every test file to a header and the committed index to --check.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const TESTING = "TESTING.md";
export const START = "<!-- test-index:start (generated by node scripts/test-index.mts --write) -->";
export const END = "<!-- test-index:end -->";

// Every test file in the tree, tracked or not yet added, as repo-relative paths in sorted order.
export function testFiles(root = ROOT): string[] {
  const out = execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard", "app", "scripts", "electron", "adapters"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
  return [...new Set(out.split("\n"))].filter((f) => (f.endsWith(".test.mts") || /(^|\/)test_[^/]+\.py$/.test(f)) && existsSync(join(root, f))).sort();
}

// The header's first sentence, or null when the file has no header in the expected shape.
export function summaryOf(file: string, text: string): string | null {
  const name = file.split("/").pop()!;
  const first = text.split("\n", 1)[0]!.trimEnd();
  const m = file.endsWith(".py") ? /^"""(\S+) (?:--|—) (.+)$/.exec(first) : /^\/\/ (\S+) — (.+)$/.exec(first);
  if (!m || m[1] !== name) return null;
  const sentence = /^(.+?\.)(?:\s|$)/.exec(m[2]!);
  return sentence ? sentence[1]! : null;
}

export function renderIndex(root = ROOT): { text: string; missing: string[] } {
  const lines: string[] = [];
  const missing: string[] = [];
  for (const f of testFiles(root)) {
    const s = summaryOf(f, readFileSync(join(root, f), "utf8"));
    if (s === null) missing.push(f);
    else lines.push(`- \`${f}\` — ${s}`);
  }
  return { text: lines.join("\n"), missing };
}

// TESTING.md with its index replaced by `index` (line endings read as "\n"); throws when the markers are missing.
export function withIndex(testing: string, index: string): string {
  const t = testing.replace(/\r\n/g, "\n");
  const a = t.indexOf(START);
  const b = t.indexOf(END);
  if (a < 0 || b < a) throw new Error(`${TESTING} has no index markers`);
  return `${t.slice(0, a + START.length)}\n${index}\n${t.slice(b)}`;
}

// Whether TESTING.md's committed index is the one the headers give.
export function indexIsCurrent(root = ROOT): boolean {
  const current = readFileSync(join(root, TESTING), "utf8").replace(/\r\n/g, "\n");
  return withIndex(current, renderIndex(root).text) === current;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { text, missing } = renderIndex();
  for (const f of missing) console.error(`${f} has no header: its first line must be "// <name> — <summary>." ("""<name> -- <summary>." in Python)`);
  if (process.argv.includes("--check")) {
    const current = indexIsCurrent();
    if (!current) console.error(`${TESTING}'s test index is out of date: run node scripts/test-index.mts --write`);
    process.exit(!current || missing.length ? 1 : 0);
  } else if (process.argv.includes("--write")) {
    const path = join(ROOT, TESTING);
    const current = readFileSync(path, "utf8");
    const next = withIndex(current, text);
    if (next !== current.replace(/\r\n/g, "\n")) writeFileSync(path, next);
    console.log(next === current.replace(/\r\n/g, "\n") ? "the test index is current" : `${TESTING}'s test index rewritten`);
  } else console.log(text);
  if (missing.length) process.exit(1);
}
